#!/bin/sh
set -e

if [ "$1" = remove ] || [ "$1" = purge ]; then
    if [ "$1" = purge ]; then
        systemctl stop kde-fan-control-daemon 2>/dev/null || true
        systemctl disable kde-fan-control-daemon 2>/dev/null || true
    fi
    systemctl daemon-reload || true
    update-desktop-database /usr/share/applications 2>/dev/null || true
    gtk-update-icon-cache -q -t /usr/share/icons/hicolor 2>/dev/null || true
fi