#!/bin/sh
set -e

if [ "$1" = configure ]; then
    systemctl daemon-reload || true
    update-desktop-database /usr/share/applications 2>/dev/null || true
    gtk-update-icon-cache -q -t /usr/share/icons/hicolor 2>/dev/null || true
fi